Fetch data
fatima-najafi/metrics-webapp-react pull request #2
Opened 2023-09-06 11:56 UTC by fatima-najafi

2023-09-06 15:33 UTC, Munsa1 requested changes
Hi @fatima-najafi, 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-09-06 15:33 UTC, Munsa1 commented on README.md
> +- [here](https://www.loom.com/share/b100af4d621e4a4190db3d32c3ff2026?sid=ebc6c048-9562-4cac-8009-41b658f56cd4)
- [ ] Great job creating a video presentation of your project as required, however, you are supposed to HIGHLIGHT a piece of code you found interesting or are proud of making. Kindly re-record your video and do so.

2023-09-06 15:33 UTC, Munsa1 commented on src/components/homepage/HomepageList.js
> +      <div className="container">
- [ ] Great job on your project it works fine. However, your design could use some improvements so as to match the given design

Given design
![image](https://github.com/fatima-najafi/metrics-webapp-react/assets/81932478/8bff4077-f827-4cad-9d4b-461f8823a019)

Your design
![image](https://github.com/fatima-najafi/metrics-webapp-react/assets/81932478/234a2f66-ede9-4bd2-8efa-24227ccc7049)

- Consider removing the white space around your cards and have them each fill up 50% of the mobile view so as to match the given design. Then you can give alternating cards the same color of grey and the other alternating cards should have a slightly lighter variation of the grey color
![image](https://github.com/fatima-najafi/metrics-webapp-react/assets/81932478/b52bc8e6-afd1-4dac-a657-699ed3a4e21b)
Notice how the cards have a color pattern where the first card is slightly lighter as compared to the next card.
- Also notice how there is no spacing between the cards in the given design. Kindly implement that as well.
- Also consider aligning your text on each card to the bottom right as is in the given design and the image to the top left corner.

- [ ] Also consider using the provided font family for your design. You are using `Poppins` whilst the given one is `gill sans` and `Lato`. This applies to all text in your app.
![image](https://github.com/fatima-najafi/metrics-webapp-react/assets/81932478/426d70eb-8e06-4e94-bc93-dbb2cc2e6ace)

2023-09-06 15:33 UTC, Munsa1 commented on src/components/details/Detailspage.js
> +            </tr>
- [ ] The same applies to the details page, kindly ensure you follow the given design.

Your design
![image](https://github.com/fatima-najafi/metrics-webapp-react/assets/81932478/c2963e32-1f45-4201-96c5-326e31946060)

Given design
![image](https://github.com/fatima-najafi/metrics-webapp-react/assets/81932478/2542fcd3-b675-43df-9080-3d2c61477a6f)

- Kindly ensure your design fills up the whole view of the mobile design, i.e. there should be no white space around your design
- The font family used should also be consistent with the given design
- The image in the details page should be aligned to the left and the text to the right as is in the given design.

2023-09-06 15:33 UTC, Munsa1 commented on src/components/navbar/Navbar.js
> +    </div>
- [ ] One of the requirements is that you write Integration tests for your application, I would advise to write for the navigation bar. Check out a similar example below

```
Sample navigation bar
// NavigationBar.js
import React from 'react';
import { Link } from 'react-router-dom';

const NavigationBar = () => {
  return (
    <nav>
      <ul>
        <li><Link to="/">Home</Link></li>
        <li><Link to="/about">About</Link></li>
        <li><Link to="/contact">Contact</Link></li>
      </ul>
    </nav>
  );
};

export default NavigationBar;
```
```
Test example

// NavigationBar.test.js
import React from 'react';
import { render, fireEvent } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import NavigationBar from './NavigationBar';

test('navigation links work correctly', () => {
  const { getByText, history } = render(
    <MemoryRouter>
      <NavigationBar />
    </MemoryRouter>
  );

  // Initially, we're on the Home page
  expect(getByText('Home')).toBeInTheDocument();
  expect(getByText('About')).toBeInTheDocument();
  expect(getByText('Contact')).toBeInTheDocument();

  // Click on the About link
  fireEvent.click(getByText('About'));
  expect(history.location.pathname).toBe('/about');

  // Click on the Contact link
  fireEvent.click(getByText('Contact'));
  expect(history.location.pathname).toBe('/contact');

  // Click on the Home link
  fireEvent.click(getByText('Home'));
  expect(history.location.pathname).toBe('/');
});
```

2023-09-07 19:06 UTC, usorfaitheloho requested changes
Hi @fatima-najafi  :thumbsup:  ,

This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.

There are still some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.giphy.com/media/dEPGknRiEniec/giphy.gif" width="500" height="250" />

## Highlights
- Fixed some changes suggested by the previous reviewer ✔️ 
<br/>
<br/>
<br/>

 ## Required Changes  :recycle: 

_Check the comments under the review._ 

***
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

* * *
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-07 19:06 UTC, usorfaitheloho commented on README.md
> + <!-- LIVE DEMO -->
As suggested by the previous reviewer, kindly HIGHLIGHT a piece of code you found interesting or are proud of making in your video, you could redo the video to state this point 😄

2023-09-07 19:06 UTC, usorfaitheloho commented on src/components/homepage/HomepageList.js
> +      <div className="container">
You did well fixing some of the problems identified by the previous reviewer, kindly  fix this one `Also consider aligning your text on each card to the bottom right as is in the given design and the image to the top left corner.`

2023-09-07 21:00 UTC, fobadara approved these changes
Hi @fatima-najafi , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![APPRVED](https://user-images.githubusercontent.com/62938735/260206857-3c93f52c-5b21-4f6f-8bc4-be158a13d3cd.gif)
## Highlights
✅ Descriptive README
✅ Descriptive PR summary
✅ Clean code

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-08 04:50 UTC, merged